# Generated by Django 3.2.3 on 2021-05-28 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.IntegerField(verbose_name='ID заявки')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('product', models.CharField(choices=[('', 'Выберите тип продукта'), ('car', 'Авто'), ('consumer', 'Потреб'), ('deposit', 'Залог'), ('mortgage', 'Ипотека')], max_length=20, verbose_name='Продукт')),
                ('phone_number', models.CharField(help_text='Номер телефона в формате 9xxxxxxxxx', max_length=10, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате 9xxxxxxxxx', regex='^[0-9]{10}$')], verbose_name='Номер телефона')),
                ('solution', models.CharField(blank=True, choices=[('', 'Решение по заявке'), ('approved', 'Одобрено'), ('denied', 'Отказано'), ('temp_denied', 'Временно отказано')], max_length=20, null=True, verbose_name='Решение')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Логи',
                'verbose_name_plural': 'Логи',
                'ordering': ('date',),
            },
        ),
        migrations.AlterField(
            model_name='data',
            name='phone_number',
            field=models.CharField(help_text='Номер телефона в формате 9xxxxxxxxx', max_length=10, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате 9xxxxxxxxx', regex='^[0-9]{10}$')], verbose_name='Номер телефона'),
        ),
    ]
