# Generated by Django 3.2.3 on 2021-05-29 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20210528_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeLog',
        ),
    ]
