# Generated by Django 3.2.3 on 2021-05-30 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table', '0005_remove_data_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Автор заявки'),
            preserve_default=False,
        ),
    ]
